# Data Mining Lab 6
This notebook includes Lab 6 work focused on machine learning techniques, evaluation metrics, and result discussion.

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('/content/Study_Hours.csv')

In [4]:
df.head()

   Hours of Study  Exam Score
0             1.2         300
1             1.7         470
2             4.0         500
3             6.0         600
4             5.5         500

In [20]:
x = df.iloc[:,:-1] #can be written as also [:,:-1] or dataset[['Hours of Study']]
y = df.iloc[:,1] #['Exam Score']

In [9]:
x

0     1.2
1     1.7
2     4.0
3     6.0
4     5.5
5     6.3
6     6.6
7     3.2
8     6.5
9     4.5
10    5.4
11    6.8
12    6.0
13    3.8
14    2.5
15    5.2
16    5.5
17    5.6
18    6.0
19    1.3
20    1.4
21    5.6
22    5.0
23    4.2
24    4.5
25    5.2
26    3.1
27    3.4
28    5.1
29    4.4
Name: Hours of Study, dtype: float64

paper er moddhe alada alada ratio te train test bhag kore result er change dekhaite hbe and reason dite hbe j kn shei ratio ta choose korsi ( karon oi ratio te accuraccy beshi)

In [21]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
lr = LinearRegression()

In [24]:
lr.fit(x_train,y_train)

LinearRegression()

In [25]:
lr.predict(x_test)

array([507.23946266, 584.98785867, 493.10339066, 606.19196667,
       443.62713866, 542.57964267])

In [26]:
y_test

2     500
28    520
13    400
10    570
26    470
24    510
Name: Exam Score, dtype: int64